Repaired TypeError
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Andrew\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Andrew\anaconda3\lib\tkinter\__init__.py", line 804, in callit
    func(*args)
TypeError: update_colors() missing 1 required positional argument: 'step'